### ISSUE TITLE
Integration with ndk (crate in rust-windowing/android-ndk-rs)

### ISSUE THREAD

**Issue by zmerp** [Hardebayho/rust_mediacodec#1]
Hi, two months ago I contributed a mediacodec module to the ndk crate (https://github.com/rust-windowing/android-ndk-rs/pull/216). Since then there have been discussions on how to make the API safer, for example decide when it's correct to assume a returned pointer is non-null (https://github.com/rust-windowing/android-ndk-rs/pull/248). I found your repository and it seems you did a lot more extensive testing to validate these assumptions.

Would you like to move your contributions to the android-ndk-rs repo as part of the ndk crate? This would make it much easier to do interop between the ndk crate and your API.

**Comment by bayo-code** [comment]
Hello. Yeah, why not?
We could do that!
